city=['Ajmer','Jaipur','Udaipur','Jodhpur']
print(city[0])
city[0]='Kota'
print(city)
city.append('Bikaner')
print(city)
city.insert(2,'Jaisalmer')
print(city)
city.remove('Jaisalmer')
print(city)
# city.pop()
# city.pop()
# print(city)
city.sort()
print(city)
city.reverse()
print(city)
# city.clear()
# print(city)
city1=city.copy()
city.append('Pali')
print(city1)
print(city[0:3])
all_city=city+city1
print(all_city)
print(len(all_city))
print(all_city.count('Jaipur'))
print(all_city.index('Jaipur'))
print(all_city.index('Jaipur',4))