city=["ajmer","jaipur","udaipur","jodhpur"]
cityall=city.copy()
print(cityall)
# city.append("bikaner")
# print(city)
# city.insert(2,"kota")
# print(city)
# city.remove("kota")
# print(city)
# city.pop(2)
# print(city)
# city.clear()
# print(city)
city.reverse()
print(city)
city.sort()
print(city)
city.extend(["bikaner","kota"])
print(city)

